name: Sean Clayton
description: Time's Person of the Year, 2006
meta_description: "Thoughts and writings from Sean Clayton."

aboutPage: true

markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'strikethrough', 'superscript']

paginate: 20
baseurl: /
domain_name: 'https://seanclayton.me'
google_analytics: 'UA-19039465-4'
disqus: false
disqus_shortname: 'your-disqus-shortname'

github_user: 'sean-clayton'
github_repo: 'sean-clayton.github.io'

email: 'sean@seanclayton.me'

# Details for the RSS feed generator
url:            'https://seanclayton.me'
author:         'Sean Clayton'
authorTwitter:  'seanybingbong'

permalink:       /:year/:title/

defaults:
  -
    scope:
      path: "" # empty string for all files
      type: pages
    values:
      layout: default
  -
    scope:
      path: "" # empty string for all files
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post
